/**
 * Launch Wizard Templates
 * 
 * Generates personalized project files based on user input.
 */

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export type LaunchData = {
  projectName: string
  tagline: string
  githubUrl: string
  authorName: string
  authorUrl: string
  appDescription: string
}

type FutureIdea = {
  title: string
  description: string
  bullets: string[]
}

// -----------------------------------------------------------------------------
// Feature Detection
// -----------------------------------------------------------------------------

const FEATURE_KEYWORDS = {
  list: ['list', 'table', 'view', 'display'],
  create: ['create', 'add', 'new', 'insert'],
  edit: ['edit', 'update', 'modify', 'change'],
  delete: ['delete', 'remove', 'trash'],
  dashboard: ['dashboard', 'overview', 'stats', 'analytics', 'metrics'],
  search: ['search', 'filter', 'find', 'query'],
  kanban: ['kanban', 'board', 'drag', 'column'],
  notifications: ['notification', 'alert', 'remind', 'notify'],
  upload: ['upload', 'image', 'file', 'attachment', 'media'],
  collaboration: ['share', 'collaborate', 'team', 'invite', 'member'],
  tasks: ['task', 'project', 'todo', 'item'],
  users: ['user', 'team', 'member', 'organization'],
} as const

function hasFeature(description: string, feature: keyof typeof FEATURE_KEYWORDS): boolean {
  const keywords = FEATURE_KEYWORDS[feature]
  return keywords.some(keyword => description.includes(keyword))
}

function escapeQuotes(str: string): string {
  return str.replace(/'/g, "\\'")
}

function truncate(str: string, maxLength: number): string {
  return str.length > maxLength ? `${str.slice(0, maxLength)}...` : str
}

// -----------------------------------------------------------------------------
// Template Generators
// -----------------------------------------------------------------------------

export function generateBuildMd(data: LaunchData): string {
  return `# ${data.projectName} Build Spec

> Generated by Launch Wizard. Cursor AI uses this to build your app.

## App Description

${data.appDescription}

## Project Foundation

Built on the Next.js Cursor Template:

| Component | Location | Status |
|-----------|----------|--------|
| Authentication | \`lib/auth.ts\` | Ready (NextAuth + Google OAuth) |
| Database | \`lib/db.ts\` | Ready (Prisma + User model) |
| UI Components | \`components/ui/\` | Ready (shadcn/ui) |
| Admin Dashboard | \`app/admin/\` | Ready (reference pattern) |
| API Routes | \`app/api/\` | Ready (pattern examples) |

## Data Models

Extend \`prisma/schema.prisma\` based on the app requirements:

\`\`\`prisma
// Existing User model — add relations as needed
model User {
  id        String   @id @default(uuid())
  email     String   @unique
  name      String?
  role      String   @default("user")
  createdAt DateTime @default(now())
  // Add relations here
}

// New models go here
\`\`\`

## Implementation Order

1. **Schema** — Define models in \`prisma/schema.prisma\`
2. **Database** — Run \`npm run db:push\` to sync
3. **API Routes** — Create CRUD endpoints in \`app/api/\`
4. **Components** — Build UI in \`components/\`
5. **Pages** — Assemble in \`app/\`
6. **Polish** — Loading states, error handling, animations

## Conventions

- Tailwind CSS for styling (\`cn()\` for conditional classes)
- Server Components by default, \`'use client'\` only when needed
- Check \`components/ui/\` before creating new primitives
- Follow existing patterns in the codebase

## Notes for Cursor

- Ask before major architectural decisions
- Keep components small and focused
- Support dark mode with \`dark:\` prefix
`
}

export function generateReadme(data: LaunchData): string {
  const authorSection = data.authorName
    ? `\n**Built by [${data.authorName}](${data.authorUrl || '#'})**\n`
    : ''
  
  const githubSection = data.githubUrl
    ? `[GitHub](${data.githubUrl})\n`
    : ''

  return `# ${data.projectName}

${data.tagline}

## Getting Started

\`\`\`bash
npm install
cp .env.example .env.local  # Configure credentials
npm run db:setup
npm run dev
\`\`\`

## Features

- **Authentication** — Google OAuth with NextAuth.js
- **Database** — Prisma ORM (SQLite dev / PostgreSQL prod)
- **UI** — shadcn/ui + Tailwind CSS
- **Dark Mode** — System-aware theming

## Project Structure

\`\`\`
app/           → Pages and API routes
components/    → React components (ui/ for shadcn)
lib/           → Utilities and config
prisma/        → Database schema
plans/         → Build spec and roadmap
\`\`\`

## Commands

| Command | Description |
|---------|-------------|
| \`npm run dev\` | Development server |
| \`npm run build\` | Production build |
| \`npm run db:push\` | Sync schema |
| \`npm run db:studio\` | Database GUI |

## Development

See \`plans/BUILD.md\` for the detailed build specification.

${authorSection}${githubSection}`
}

export function generateSiteConfig(data: LaunchData): string {
  const name = escapeQuotes(data.projectName)
  const tagline = escapeQuotes(data.tagline)
  const github = escapeQuotes(data.githubUrl)
  
  const footerLink = data.githubUrl
    ? `{ label: 'GitHub', href: '${github}' },`
    : `// { label: 'GitHub', href: 'https://github.com/you/repo' },`

  return `/**
 * Site Configuration
 * 
 * Central config for site-wide content. Edit here to update everywhere.
 */

export type FooterLink = {
  label: string
  href?: string
  type?: 'email'
}

export const SITE = {
  // Branding
  name: '${name}',
  tagline: '${tagline}',
  description: '${tagline}',
  
  // Contact
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || '',
  
  // URLs
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  github: '${github}',
  
  // Footer
  footerLinks: [
    ${footerLink}
  ] as FooterLink[],
  
  // Homepage features
  features: [
    { title: 'Authentication', description: 'Google OAuth with role-based access.', icon: 'lock' },
    { title: 'Database', description: 'Prisma ORM with SQLite/PostgreSQL.', icon: 'users' },
    { title: 'UI Components', description: 'shadcn/ui ready to customize.', icon: 'palette' },
    { title: 'Dark Mode', description: 'System-aware theme switching.', icon: 'moon' },
  ],
}
`
}

export function generateCursorPrompt(data: LaunchData): string {
  return `I want to build ${data.projectName}: ${data.tagline}

${data.appDescription}

Read plans/BUILD.md for the full spec.

FIRST: Clean up the template by running:
npm run cleanup

This removes template files (stories/, launch wizard) and prepares the project for building.
The deploy guide at /deploy is kept — use it when you're ready to ship.

THEN: Replace app/page.tsx with a clean homepage for ${data.projectName}.

EXISTING INFRASTRUCTURE (use these):
- Auth: lib/auth.ts (NextAuth + Google OAuth)
- Database: lib/db.ts (Prisma + User model)
- UI: components/ui/ (shadcn/ui)
- Patterns: app/admin/ and app/api/

BUILD ORDER:
1. Run cleanup script (above)
2. Create clean homepage
3. Extend prisma/schema.prisma with new models
4. Create API routes in app/api/
5. Build UI components
6. Assemble pages

Ask before major architectural decisions.`
}

export function generateTomorrowMd(data: LaunchData): string {
  const desc = data.appDescription.toLowerCase()
  
  const tasks: string[] = [
    'Review plans/BUILD.md with Cursor',
    'Design Prisma schema for new models',
    'Run `npm run db:push` to sync database',
  ]
  
  if (hasFeature(desc, 'list')) tasks.push('Create list/table view component')
  if (hasFeature(desc, 'create')) tasks.push('Build create/add form')
  if (hasFeature(desc, 'edit')) tasks.push('Build edit form')
  if (hasFeature(desc, 'delete')) tasks.push('Add delete with confirmation dialog')
  if (hasFeature(desc, 'dashboard')) tasks.push('Create dashboard with key metrics')
  if (hasFeature(desc, 'search')) tasks.push('Implement search and filtering')
  if (hasFeature(desc, 'kanban')) tasks.push('Build kanban board with drag-and-drop')
  if (hasFeature(desc, 'notifications')) tasks.push('Set up notification system')
  if (hasFeature(desc, 'upload')) tasks.push('Implement file upload')
  if (hasFeature(desc, 'collaboration')) tasks.push('Add sharing/collaboration features')
  
  tasks.push('Add loading and error states', 'Test core user flows')

  const taskList = tasks.map(t => `- [ ] ${t}`).join('\n')

  return `# Tomorrow

> Immediate tasks for ${data.projectName}. Generated from your app description.

## Build Tasks

${taskList}

## Setup (if needed)

- [ ] Configure Google OAuth credentials
- [ ] Set up .env.local
- [ ] Run \`npm run db:setup\`

## Context

${data.tagline}

${truncate(data.appDescription, 200)}
`
}

export function generateFutureMd(data: LaunchData): string {
  const desc = data.appDescription.toLowerCase()
  const ideas: FutureIdea[] = []
  
  if (hasFeature(desc, 'tasks')) {
    ideas.push({
      title: 'Recurring Tasks',
      description: 'Support for repeating tasks.',
      bullets: ['Daily/weekly/monthly recurrence', 'Custom patterns', 'Auto-generation'],
    })
    ideas.push({
      title: 'Time Tracking',
      description: 'Track time spent on work.',
      bullets: ['Start/stop timer', 'Manual entry', 'Reports'],
    })
  }
  
  if (hasFeature(desc, 'users')) {
    ideas.push({
      title: 'Team Features',
      description: 'Enhanced collaboration.',
      bullets: ['Workspaces', 'Permissions', 'Activity feed', 'Comments'],
    })
  }
  
  if (hasFeature(desc, 'dashboard')) {
    ideas.push({
      title: 'Advanced Analytics',
      description: 'Deeper insights.',
      bullets: ['Custom date ranges', 'CSV/PDF export', 'Charts', 'Scheduled reports'],
    })
  }
  
  ideas.push(
    {
      title: 'Email Notifications',
      description: 'Keep users informed.',
      bullets: ['Resend/SendGrid', 'Digest emails', 'Preferences'],
    },
    {
      title: 'Mobile App',
      description: 'Native experience.',
      bullets: ['React Native', 'Push notifications', 'Offline support'],
    },
    {
      title: 'API & Integrations',
      description: 'Connect with other tools.',
      bullets: ['REST API', 'Webhooks', 'Zapier', 'Calendar sync'],
    },
    {
      title: 'Monetization',
      description: 'Revenue options.',
      bullets: ['Stripe billing', 'Usage limits', 'Team plans'],
    }
  )

  const ideasMd = ideas
    .map(idea => {
      const bullets = idea.bullets.map(b => `- ${b}`).join('\n')
      return `## ${idea.title}\n\n${idea.description}\n\n${bullets}`
    })
    .join('\n\n---\n\n')

  return `# Future

> Long-term ideas for ${data.projectName}. Add your own as you build.

---

${ideasMd}

---

## Your Ideas

_Add ideas here as they come up._
`
}
